version: 2.1
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies (if needed)
          command: pip install -r requirements.txt
      - run:
          name: Run tests (example)
          command: python -c "print('Tests passed')"
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
