version: 2.1

orbs: 
  snyk: snyk/snyk@2.2.0
  
jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dependencies (if needed)
          command: pip install -r requirements.txt
      - run:
          name: Run tests (example)
          command: python -c "print('Tests passed')"
      - snyk/scan: 
          fail-on-issues: false
      - setup_remote_docker
      - run: docker build -t python_project:latest .
          
workflows:
  version: 2
  build-workflow:
    jobs:
      - build
